# Generated by Django 3.0 on 2021-07-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20210703_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
